apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: v14-singularity
spec:
  source:
    repoURL: https://github.com/your/repo
    path: v14-singularity/infra/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
